### ISSUE TITLE
The component is not rerendered when the value becomes empty again

### ISSUE THREAD

**Issue by tiu93** [40818419/react-code-input#102]
Hi. I have this case:
I fill in the wrong code. Next, I have code validation.
If the pin code is incorrect, I write value = "" to state and pass it to ReactCodeInput.
But ReactCodeInput is not rerender. Fields are also filled with incorrect code.

You can see my example here:
https://codesandbox.io/s/react-code-input-example-td82z?file=/src/App.js

**Comment by maharjanaman** [comment]
I have a similar issue with redux-form. Resetting or destroying form, removes the value from redux but values are still showing in the input fields.

**Comment by Pixcell** [comment]
Any news on this? Or workaround?

**Comment by Pixcell** [comment]
https://github.com/40818419/react-code-input/issues/69#issuecomment-506657412

**Comment by tiu93** [comment]
> [# 69 (комментарий)](https://github.com/40818419/react-code-input/issues/69#issuecomment-506657412)

Is it worked for you?
I tried it. In my case, the input value is overwritten in the state, but the rerendering does not occur.

**Comment by Pixcell** [comment]
If that's the case, you can always force a render ;)

```
const [render, setRender] = React.useState(true)


setRender(v => !v) // This will force you component to re-render
```

I use this technique whenever I need to force re-rendering (after updating a ref, or an internal state)

**Comment by tiu93** [comment]
> If that's the case, you can always force a render ;)
> 
> ```
> const [render, setRender] = React.useState(true)
> 
> 
> setRender(v => !v) // This will force you component to re-render
> ```
> 
> I use this technique whenever I need to force re-rendering (after updating a ref, or an internal state)

It is worked. Thank you!)
