### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by mglidden** [40818419/react-code-input#11]
We're working on transitioning to React 16, and this is our last remaining package that still requires React 15 :)

Do you know of anything significant that blocks updating? I'm happy to submit a pull request if you'd like.

**Comment by 40818419** [comment]
@mglidden hey, i added react 16 compatibility in last master, would be nice if you could test it locally. Also we need to get rid of "refs", any idea?

**Comment by 40818419** [comment]
Now "Prevent using string references (react/no-string-refs)" is also fixed

**Comment by mglidden** [comment]
Master works for me – thanks!

I think that React (and react-dom) should be in peerDependencies – as is, it causes npm/yarn to install 2 copies of react if the user is using a slightly different version of React.

**Comment by 40818419** [comment]
you mean to let is like it was?: 
`  "peerDependencies": {
     "react": "^15.5.4",
    "react-dom": "^15.5.4"
  }`

**Comment by mglidden** [comment]
It should be:
"peerDependencies": { "react": "^15.4.4 || ^16.0.0", "react-dom": "^15.4.4 || ^16.0.0" }

Just putting 15.4.4 will allow it to work, but throw a warning when installing with react 16. Since the package is compatible with both, you can say it works with either.

**Comment by 40818419** [comment]
Well, i think those who is using react <16.0.0 will need to downgrade version of this lib, simple as that.

**Comment by mglidden** [comment]
The latest version works correctly on both React 15 and 16 though – so why not leave version 15 supported as well?

**Comment by 40818419** [comment]
true, thanks for your time, released
