### ISSUE TITLE
Bug in input

### ISSUE THREAD

**Issue by mehrdaad** [40818419/react-code-input#12]
Trying to start inputting a number in the last cell changes the next focused cell to the second cell and unpredictable behavior happens.

**Comment by 40818419** [comment]
please provide user-agent information and ideally a animation to reproduce this bug.

Here is what i see: https://www.screencast.com/t/GieUu5pN

**Comment by mehrdaad** [comment]
User-agent: Chrome 63
Also tested on Firefox 59.0b  
https://www.screencast.com/t/7ovSVSKNKT

**Comment by mehrdaad** [comment]
My intuitive say that you keep an index indicating which item should be selected next by index+1 and that index is initially 0. When user selects non first cell the next cell is wrongly calculated as 1 which is second cell.  
Maybe you should keep a foucs listner and update state on index on that index change.

**Comment by 40818419** [comment]
I'll investigate but feel free to submit PR

**Comment by mehrdaad** [comment]
Alright, please add bug label to the issue

**Comment by Julia-Lavrova** [comment]
@mehrdaad May be,  this [PR](https://github.com/40818419/react-code-input/pull/20) resolve your problem

**Comment by mehrdaad** [comment]
@Julia-Lavrova Thank you very much. I never did made time to submit a pr. Thank you.
