### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by mgreca** [40818419/react-code-input#124]
When trying to use this library in a project with React 17:

``` 
Could not resolve dependency:
peer react@"^15.5.4 || ^16.2.0" from react-code-input@3.10.0
```

**Comment by aamirnbs** [comment]
I am facing the same issue, anyone found any workaround?

`Could not resolve dependency:
peer react@"^15.5.4 || ^16.2.0" from react-code-input@3.10.0`

**Comment by mgreca** [comment]
The only workaround is to do the `npm install --legacy-peer-deps`. But it is not the solution, we need the package.json to have the `peerDependencies` referencing react 17

**Comment by aamirnbs** [comment]
Thanks and agreed with you @mgreca

**Comment by mgreca** [comment]
I've created a PR for this: #125

**Comment by aamirnbs** [comment]
Appreciated your efforts on it @mgreca 
Any idea when we will be able to install it officially?

**Comment by mgreca** [comment]
I don't know. 
@40818419 how can we help you to make a new version with this change?

**Comment by 40818419** [comment]
new version will be released today, thanx @mgreca

**Comment by 40818419** [comment]
@aamirnbs please use https://www.npmjs.com/package/react-code-input/v/3.10.1

**Comment by aamirnbs** [comment]
[3.10.1](https://www.npmjs.com/package/react-code-input/v/3.10.1) worked like a charm.
Thanks @mgreca @40818419

**Comment by 40818419** [comment]
Awesome, i'll close this issue
