### ISSUE TITLE
Up/down arrow key cause 1/0 when type=number

### ISSUE THREAD

**Issue by roberthodgen** [40818419/react-code-input#14]
Chrome 64.

When `type='number'` an Up Arrow key press causes a `1` to appear in the field and focus advances to the next field. When the Down Arrow key is pressed a `0` is entered.

**Comment by 40818419** [comment]
WTF, indeed.. good catch!!

**Comment by 40818419** [comment]
Actually it is a default behavior for number field, but it is confusing, so i agree with you.
Fixed in 12d1d35
