### ISSUE TITLE
Non-unique IDs when using multiple ReactCodeInputs

### ISSUE THREAD

**Issue by jacobpenny** [40818419/react-code-input#26]
If you have more than one `ReactCodeInput` on a page the input elements will wind up with duplicate IDs. If `type` is `password` then Chrome (Version 66.0.3359.181 here) will actually complain with something like `[DOM] Found 2 elements with non-unique id #0: (More info: https://goo.gl/9p2vKq) `.

Does it make sense to add an `idPrefix` prop or similar to avoid this? I'd be glad to submit a PR if that sounds like a decent solution.

**Comment by 40818419** [comment]
thanx, really good catch! will introduce guid for that!

**Comment by 40818419** [comment]
@jacobpenny please test GH-29
