### ISSUE TITLE
🐛Input type number allows for dashes `-`

### ISSUE THREAD

**Issue by A-Tokyo** [40818419/react-code-input#27]
### Description
- When input `type` is `number`, pressing dash (`-`) populates the field.
- Same behavior happens with dots `.`
- The reason is basically that HTML input type `number` allows for dots and dashes, however, I don't think it's useful in this component (people accidentally press `-` instead of `0` sometimes).

### Expected behavior
- `-` should not be valid to enter

### Preview
<img width="374" alt="preview" src="https://user-images.githubusercontent.com/12428415/40857883-cce688c4-65dc-11e8-970a-edd9fde37d7c.png">

### Extra info
Version: `"react-code-input": "^3.2.0",`

Happy to open a PR!

**Comment by 40818419** [comment]
@A-Tokyo  please feel free to contribute, thanx!
