### ISSUE TITLE
Dont working in the server

### ISSUE THREAD

**Issue by Asgator** [40818419/react-code-input#36]
lib/ string 
```}(window, function(__WEBPACK_EXTERNAL_MODULE_61__) {```

Error 
```
ReferenceError: window is not defined
    at Object../node_modules/react-code-input/lib/ReactCodeInput.js
```

**Comment by 40818419** [comment]
what do you think, will this fix it:

```js
if (typeof window === 'undefined') {
    global.window = {}
}
```

**Comment by 40818419** [comment]
@Asgator please test this PR and tell me if it's working for you.

**Comment by Asgator** [comment]
@40818419 Okay, thx, in monday.

**Comment by 40818419** [comment]
cool article, will think about it! thanx
