### ISSUE TITLE
Allow prop to force all uppercase

### ISSUE THREAD

**Issue by bill-vatomic** [40818419/react-code-input#45]
Hello, I'd like to see a way to be able to force all the characters to appear as uppercase. I have a PR ready that adds a new prop called 'forceUppercase: boolean' that just changes the input on handleOnChange to be uppercase. Do you find this useful? I would need it for my application.

**Comment by 40818419** [comment]
hi @bill-vatomic , if you found a use-case for that, i don't see any reasons why not to have this functionality.
please make sure tests are passing and your PR is linked to this issue.

**Comment by bill-vatomic** [comment]
Hello! I've added a testcase for the forceUppercase prop. The PR for this issue is here: #46 

The motive for this is my application which generates codes that are always uppercase. This allows the user to type either case and still match their invite code.

**Comment by Samesh** [comment]
Hi. Has this been added yet? I tried it out, but it didn't seem to work.
`<ReactCodeInput
                  type='text'
                  fields={6}
                  autoFocus={false}
                  forceUppercase={true}
                />`

**Comment by 40818419** [comment]
https://github.com/40818419/react-code-input/blob/master/src/ReactCodeInput.js

here you can find your code, i would suggest you add some unit tests

**Comment by Samesh** [comment]
Didn't work. I even tried changing the initial value from false to true. It's cool. Thanks anyway

**Comment by bill-vatomic** [comment]
There actually is a unit test for it, but I will take a look at this when I wake up tomorrow morning.

**Comment by bill-vatomic** [comment]
Did the build for this PR fail or something? I checked again, and this works as expected when I test on the dev-page using 'yarn start'. You can checkout my code and run the dev server, and see it working.

**Comment by 40818419** [comment]
@Samesh @bill-vatomic  i added "forceUpdate" story. 

https://40818419.github.io/react-code-input/?selectedKind=ReactCodeInput&selectedStory=Force%20Uppercase

PS: if you look at action logger, values are also uppercased.

i think we can close this issue

**Comment by trujic1000** [comment]
Would be helpful if you updated API on your README to show forceUppercase prop! I found a solution here but would have spent way less time if the info was at the right place.
