### ISSUE TITLE
🐛input type `number` allows for text input in Safari and Firefox

### ISSUE THREAD

**Issue by A-Tokyo** [40818419/react-code-input#47]
### Description
- input type `number` allows for text input in Safari and Firefox

### Expected behavior
- When input type is `number` user should not be able to add text

### Preview
-  <img width="932" alt="typenumber-bug-safari-firefox" src="https://user-images.githubusercontent.com/12428415/45212769-a26d3900-b28d-11e8-84c2-1c00763e1e92.png">

### Extra info
Version: `"react-code-input": "^3.5.0",`

**Comment by A-Tokyo** [comment]
Do you think this maybe a react issue? I tested the regular expression in both safari and firefox console and it works fine. 
```js
'aaa'.replace(/[^\d]/g, '');
// properly returns ''
```

**Comment by stefandimovbulpros** [comment]
I just experienced the same issue in Chrome. Char 'e' is the only one I can type in. When I do that the onChange callback isn't fired. Afterwards if I go to the next input and add a number value - onChange callback fires and the first input with the chars is cleared.

It looks like there is a small hole somewhere.

**Comment by 40818419** [comment]
@A-Tokyo @stefandimovbulpros interesting issue, will also investigate that

**Comment by rupin-k** [comment]
@stefandimovbulpros  - I have exactly the same issue- please see screenshot. Thanks.
![screen shot 2018-09-26 at 11 01 46 am](https://user-images.githubusercontent.com/36821689/46099566-f5932700-c17b-11e8-8f67-a025a7eb20ec.png)

**Comment by rupin-k** [comment]
@40818419 - Another issue with Input type="number" is that for each input field there is a up-down arrow appears to increase/decrease the number.

Is there is a fix to avoid this?
![screen shot 2018-09-26 at 12 07 10 pm](https://user-images.githubusercontent.com/36821689/46103150-0005ee80-c185-11e8-82b4-4e8c066e3fec.png)

**Comment by benbonnet** [comment]
Hello,
am still able to see the issue on firefox (see caption https://dzwonsemrish7.cloudfront.net/items/2S3K2i2X043z0Y3m1B0p/Capture%20d%E2%80%99e%CC%81cran%202018-10-08%20a%CC%80%2013.11.35.png)

I just checked, on 3.8.0 (latest version on npm).

We have this basic use :

```
<ReactCodeInput
                  type="number"
                  fields={4}
                  onChange={this.onChangeCode}
                  value={code}
                />
```
Is there something missing to have it working correctly ?
