### ISSUE TITLE
next.js issue still appear

### ISSUE THREAD

**Issue by Lurtt** [40818419/react-code-input#68]
If I use dynamic import it works but when I add prop like onChange, style, inputStyle it happens again.

```
import dynamic from 'next/dynamic'
const ReactCodeInput = dynamic(import('react-code-input'))

...
<ReactCodeInput
  type="number"
  fields={5}
  onChange={e => console.log('xxx', e.target.value)}
  style={{ display: 'grid' }}
  inputStyle={{}}
/>
...
```

Note: and it also happen whenever I refresh the browser :/

_Originally posted by @Lurtt in https://github.com/40818419/react-code-input/issues/66#issuecomment-435408085_

**Comment by Lurtt** [comment]
Ok I fixed that... **important** note to readme
the `ssr: false` option is required!

```
const ReactCodeInput = dynamic(import('react-code-input'), {
  ssr: false,
})
```

**Comment by 40818419** [comment]
but you can create pr with `ssr: false`
