### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by thakuranujsingh** [40818419/react-code-input#81]
Hi could you help me, How can I declare the types for react-code-input

**Comment by dewaleolaoye** [comment]
This issue is still here, does that mean the package does not support Typescript at the moment?

**Comment by 40818419** [comment]
@thakuranujsingh can i close this issue?

**Comment by thakuranujsingh** [comment]
@40818419 yes you cab close it, thanks 👍

**Comment by arpih** [comment]
Hi, is the issue(package does not support Typescript) actual yet?
