### ISSUE TITLE
error compiling into react app

### ISSUE THREAD

**Issue by rdews** [40818419/react-code-input#9]
Cannot find module '/Users/digit/Sites/react-code-input/node_modules/react-hot-api/modules/index.js' from '/Users/rdewsbury/iogc3/server/node_modules/react-code-input/lib'

Should /Users/digit/Sites be hardcoded in here?

**Comment by 40818419** [comment]
Well, `example.js` is compiled file. Execute `npm run build` - this gonna resolve the issue
